-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: "6b1aa19425b35f8c34f43ada8f1045b028dc19a5"
    hooks:
    # keep ids alphabetical! see http://pre-commit.com/hooks.html
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
        files: \.py$
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
        files: \.(py|sh)$
    -   id: flake8
        files: \.py$
        args: ['--ignore=E128']
        exclude: local\.py$  # ignore config settings
    -   id: name-tests-test
        files: tests/.+\.py$
        args: ['--django']  # Use args: ['--django'] to match test*.py instead.
    -   id: pretty-format-json
    -   id: trailing-whitespace
        files: \.(py|sh|yaml|txt)$
    -   id: requirements-txt-fixer