sudo: true
language: python
cache:
  pip: true
python:
  - "3.4.3"
before_script:
  - psql -c 'create database travisci;' -U postgres
install:
  - pip install -r requirements/test.txt
script: "python manage.py test"
notifications:
  email:
    recipients:
      - jeffshek@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
